// resources/js/Layouts/AuthenticatedLayout.vue
<template>
  <div class="min-h-screen bg-base-200 text-base-content dark:bg-base-300 dark:text-base-100 relative">
    <transition
      enter-active-class="transition ease-out duration-300"
      enter-from-class="opacity-0 translate-y-2 scale-95"
      enter-to-class="opacity-100 translate-y-0 scale-100"
      leave-active-class="transition ease-in duration-200"
      leave-from-class="opacity-100 translate-y-0 scale-100"
      leave-to-class="opacity-0 -translate-y-1 scale-95"
    >
      <div
        v-if="flash.success && showFlash"
        class="toast toast-top toast-end z-50"
      >
        <div class="alert alert-success flex items-center gap-2 bg-green-500 text-white">
          <span class="text-white">{{ flash.success }}</span>
          <button
            type="button"
            class="btn btn-xs btn-ghost text-white/80 hover:text-white ml-2"
            @click="showFlash = false"
          >
            ✕
          </button>
        </div>
      </div>
    </transition>
    <header v-if="header" class="bg-base-100 dark:bg-base-200 shadow">
      <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
        <slot name="header">{{ header }}</slot>
      </div>
    </header>
    <main><slot /></main>
  </div>
</template>

<script setup>
import { ref, computed, watch, onUnmounted } from 'vue';
import { Link, usePage, router } from '@inertiajs/vue3';
import ApplicationLogo from '@/Components/ApplicationLogo.vue';
import Dropdown from '@/Components/Dropdown.vue';
import NavLink from '@/Components/NavLink.vue';
import ResponsiveNavLink from '@/Components/ResponsiveNavLink.vue';
import ThemeToggle from '@/Components/ThemeToggle.vue';
import DropdownTrigger from '@/Components/Dropdown.vue';
import DropdownContent from '@/Components/Dropdown.vue';
import DropdownLink from '@/Components/DropdownLink.vue';

const props = defineProps({
  header: String
});

const page = usePage();
const user = computed(() => page.props.auth.user);
const flash = computed(() => page.props.flash || {});
const showingNavigationDropdown = ref(false);
const showFlash = ref(false);
let flashTimeout = null;

watch(
  () => page.props.flash,
  (flashObj) => {
    if (flashObj?.success) {
      showFlash.value = false;
      if (flashTimeout) clearTimeout(flashTimeout);
      setTimeout(() => {
        showFlash.value = true;
        flashTimeout = setTimeout(() => {
          showFlash.value = false;
        }, 3000);
      }, 10);
    }
  },
  { immediate: true }
);

onUnmounted(() => {
  if (flashTimeout) clearTimeout(flashTimeout);
});
</script>

<style scoped>
</style>

// resources/js/Layouts/AuthenticatedLayout.jsx
import ApplicationLogo from '@/Components/ApplicationLogo';
import Dropdown from '@/Components/Dropdown';
import NavLink from '@/Components/NavLink';
import ResponsiveNavLink from '@/Components/ResponsiveNavLink';
import { Link, usePage } from '@inertiajs/react';
import { useState } from 'react';
import ThemeToggle from '@/Components/ThemeToggle';

export default function AuthenticatedLayout({ header, children }) {
    const user = usePage().props.auth.user;

    const [showingNavigationDropdown, setShowingNavigationDropdown] =
        useState(false);

    return (
        <div className="min-h-screen bg-base-200 text-base-content dark:bg-base-300 dark:text-base-100">
            <nav className="navbar bg-base-100 dark:bg-base-200">
                <div className="flex-1">
                    <Link href="/" className="btn btn-ghost normal-case text-xl">
                        <ApplicationLogo className="h-9 w-auto" />
                    </Link>
                </div>
                <div className="flex-none hidden sm:flex items-center">
                    <ThemeToggle />
                    <NavLink
                        href={route('dashboard')}
                        active={route().current('dashboard')}
                        className="btn btn-ghost ml-2"
                    >
                        Dashboard
                    </NavLink>
                    <Dropdown>
                        <Dropdown.Trigger>
                            <button className="btn btn-ghost ml-2">
                                {user.name}
                                <svg
                                    className="ml-1 h-4 w-4"
                                    xmlns="http://www.w3.org/2000/svg"
                                    viewBox="0 0 20 20"
                                    fill="currentColor"
                                >
                                    <path
                                        fillRule="evenodd"
                                        d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                                        clipRule="evenodd"
                                    />
                                </svg>
                            </button>
                        </Dropdown.Trigger>
                        <Dropdown.Content>
                            <Dropdown.Link href={route('profile.edit')}>
                                Profile
                            </Dropdown.Link>
                            <Dropdown.Link
                                href={route('logout')}
                                method="post"
                                as="button"
                            >
                                Log Out
                            </Dropdown.Link>
                        </Dropdown.Content>
                    </Dropdown>
                </div>
                <div className="flex-none sm:hidden">
                    <button
                        onClick={() =>
                            setShowingNavigationDropdown(
                                (previousState) => !previousState,
                            )
                        }
                        className="btn btn-square btn-ghost"
                    >
                        {showingNavigationDropdown ? (
                            <svg
                                className="h-6 w-6"
                                fill="none"
                                stroke="currentColor"
                                viewBox="0 0 24 24"
                            >
                                <path
                                    strokeLinecap="round"
                                    strokeLinejoin="round"
                                    strokeWidth="2"
                                    d="M6 18L18 6M6 6l12 12"
                                />
                            </svg>
                        ) : (
                            <svg
                                className="h-6 w-6"
                                fill="none"
                                stroke="currentColor"
                                viewBox="0 0 24 24"
                            >
                                <path
                                    strokeLinecap="round"
                                    strokeLinejoin="round"
                                    strokeWidth="2"
                                    d="M4 6h16M4 12h16M4 18h16"
                                />
                            </svg>
                        )}
                    </button>
                </div>
                {showingNavigationDropdown && (
                    <div className="menu menu-vertical p-2 bg-base-100">
                        <ThemeToggle />
                        <Link
                            href={route('dashboard')}
                            className="btn btn-ghost"
                        >
                            Dashboard
                        </Link>
                        <Link href={route('profile.edit')} className="btn btn-ghost">
                            Profile
                        </Link>
                        <Link
                            href={route('logout')}
                            method="post"
                            as="button"
                            className="btn btn-ghost"
                        >
                            Log Out
                        </Link>
                    </div>
                )}
            </nav>

            {header && (
                <header className="bg-base-100 dark:bg-base-200 shadow">
                    <div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
                        {header}
                    </div>
                </header>
            )}

            <main>{children}</main>
        </div>
    );
}
