// resources/js/Pages/Auth/Login.vue
<template>
  <Head title="Log in" />
  <div class="login-bg">
    <div class="login-inspiration-container">
      <div class="login-inspiration-form">
        <div class="login-inspiration-header">
          <div class="login-inspiration-branding">
            <img :src="logoUrl" alt="sTracker Logo" class="login-inspiration-logo" />
            <div>
              <div class="login-inspiration-brand">sTracker</div>
              <p class="login-inspiration-brand-copy">Track income, expenses, and trends in one place.</p>
            </div>
          </div>
          <div class="login-inspiration-header-actions">
            <span class="login-inspiration-register">
              Don't have an account?
              <Link :href="route('register')" class="login-inspiration-register-link">Register</Link>
            </span>
          </div>
        </div>
        <div class="login-inspiration-card">
          <div class="login-inspiration-card-header">
            <span class="login-inspiration-eyebrow">Welcome back</span>
            <div class="login-inspiration-title">Sign in to your finance workspace</div>
            <p class="login-inspiration-description">
              Access your transactions, recent activity, and visual reports with one secure login.
            </p>
            <div class="login-inspiration-chip-row">
              <span class="login-inspiration-chip">Secure login</span>
              <span class="login-inspiration-chip">Real-time overview</span>
              <span class="login-inspiration-chip">Fast access</span>
            </div>
          </div>
          <div v-if="status" class="login-inspiration-status">
            {{ status }}
          </div>
          <form @submit.prevent="submit" class="login-inspiration-form-fields">
            <div class="login-inspiration-inputs">
              <div>
                <InputLabel htmlFor="email" value="Email Address" class="login-label" />
                <TextInput
                  id="email"
                  type="email"
                  name="email"
                  v-model="form.email"
                  autocomplete="username"
                  :isFocused="true"
                  placeholder="Email"
                  class="login-input"
                  required
                />
                <InputError :message="form.errors.email" class="mt-1" />
              </div>
              <div>
                <InputLabel htmlFor="password" value="Password" class="login-label" />
                <TextInput
                  id="password"
                  type="password"
                  name="password"
                  v-model="form.password"
                  autocomplete="current-password"
                  placeholder="Password"
                  class="login-input"
                  required
                />
                <InputError :message="form.errors.password" class="mt-1" />
              </div>
            </div>
            <div class="login-inspiration-helper-box">
              <strong>Quick tip:</strong> Use the email and password from your registered account to continue where you left off.
            </div>
            <div class="login-inspiration-actions">
              <div class="login-checkbox-row login-inspiration-checkbox-row">
                <Checkbox
                  id="remember"
                  name="remember"
                  v-model="form.remember"
                />
                <label for="remember" class="login-checkbox-label">
                  Keep me logged in
                </label>
                <Link v-if="canResetPassword" :href="route('password.request')" class="login-inspiration-forgot">Forgot password?</Link>
              </div>
              <PrimaryButton class="login-btn login-inspiration-btn" :disabled="form.processing">
                {{ form.processing ? 'Signing in...' : 'Log In' }}
              </PrimaryButton>
            </div>
          </form>
          <div class="login-inspiration-support-row">
            <span class="login-inspiration-support-text">Simple, secure, and designed for daily finance tracking.</span>
          </div>
        </div>
        <div class="login-inspiration-footer">© 2026 sTracker.</div>
      </div>

      <div class="login-inspiration-preview">
        <div class="login-inspiration-preview-glow login-inspiration-preview-glow-one"></div>
        <div class="login-inspiration-preview-glow login-inspiration-preview-glow-two"></div>
        <div class="login-inspiration-image-showcase">
          <div class="login-inspiration-dashboard-frame">
            <img
              :src="dashboardPreviewUrl"
              alt="sTracker dashboard preview"
              class="login-inspiration-preview-img"
            />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import dashboardPreviewUrl from '@/../../public/images/dashboard-preview.png';
import logoUrl from '@/../../public/images/stracker-logo.png';
import Checkbox from '@/Components/Checkbox.vue';
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import TextInput from '@/Components/TextInput.vue';
import { Head, Link, useForm } from '@inertiajs/vue3';

const props = defineProps({
  status: String,
  canResetPassword: Boolean
});

const form = useForm({
  email: '',
  password: '',
  remember: false
});

function submit() {
  form.post('/login', {
    onFinish: () => form.reset('password'),
  });
}
</script>

<style scoped>
@import '../../../css/login.css';
</style>

// resources/js/Pages/Auth/Login.jsx
import Checkbox from '@/Components/Checkbox';
import InputError from '@/Components/InputError';
import InputLabel from '@/Components/InputLabel';
import PrimaryButton from '@/Components/PrimaryButton';
import TextInput from '@/Components/TextInput';
import { Head, Link, useForm } from '@inertiajs/react';

// Modern minimalist login page component.
// Props are injected by the server-side controller (status & canResetPassword).
export default function Login({ status, canResetPassword }) {
    // useForm hook manages form state, submission, and error handling
    const { data, setData, post, processing, errors, reset } = useForm({
        email: '',
        password: '',
        remember: false,
    });

    // Handle form submission to the server
    const submit = (e) => {
        e.preventDefault();
        post(route('login'), {
            onFinish: () => reset('password'),
        });
    };

    return (
        <div className="min-h-screen flex items-center justify-center bg-base-200 px-4 py-12">
            <Head title="Log in" />

            <div className="w-full max-w-md">
                <div className="text-center mb-8">
                    <h1 className="text-3xl font-bold">Welcome Back</h1>
                    <p className="text-sm">Sign in to your account to continue</p>
                </div>

                <div className="card shadow-lg">
                    <div className="card-body">
                        {status && (
                            <div className="alert alert-success mb-4">
                                <span>{status}</span>
                            </div>
                        )}

                        <form onSubmit={submit} className="space-y-5">
                            <div>
                                <InputLabel htmlFor="email" value="Email Address" />
                                <TextInput
                                    id="email"
                                    type="email"
                                    name="email"
                                    value={data.email}
                                    autoComplete="username"
                                    isFocused={true}
                                    onChange={(e) => setData('email', e.target.value)}
                                    placeholder="you@example.com"
                                />
                                <InputError message={errors.email} className="mt-1" />
                            </div>

                            <div>
                                <InputLabel htmlFor="password" value="Password" />
                                <TextInput
                                    id="password"
                                    type="password"
                                    name="password"
                                    value={data.password}
                                    autoComplete="current-password"
                                    onChange={(e) => setData('password', e.target.value)}
                                    placeholder="••••••••"
                                />
                                <InputError message={errors.password} className="mt-1" />
                            </div>

                            <div className="flex items-center">
                                <Checkbox
                                    id="remember"
                                    name="remember"
                                    checked={data.remember}
                                    onChange={(e) => setData('remember', e.target.checked)}
                                />
                                <label
                                    htmlFor="remember"
                                    className="ml-2 select-none text-sm cursor-pointer"
                                >
                                    Keep me logged in
                                </label>
                            </div>

                            <PrimaryButton
                                className="w-full"
                                disabled={processing}
                            >
                                {processing ? 'Signing in...' : 'Sign In'}
                            </PrimaryButton>
                        </form>

                        <div className="divider">OR</div>

                        <div className="text-center text-sm">
                            {canResetPassword && (
                                <Link
                                    href={route('password.request')}
                                    className="underline"
                                >
                                    Forgot password?
                                </Link>
                            )}
                            <span className="mx-1">·</span>
                            <Link href={route('register')} className="underline">
                                Create account
                            </Link>
                        </div>
                    </div>
                </div>

                <p className="mt-6 text-center text-xs">
                    By signing in, you agree to our terms of service
                </p>
            </div>
        </div>
    );
}
