// resources/js/Pages/Auth/Register.jsx
import InputError from '@/Components/InputError';
import InputLabel from '@/Components/InputLabel';
import PrimaryButton from '@/Components/PrimaryButton';
import TextInput from '@/Components/TextInput';
import { Head, Link, useForm } from '@inertiajs/react';

// Modern minimalist registration page for brand new users.
// The form is managed by Inertia's `useForm` hook.
export default function Register() {
    // useForm hook manages all form state and submission logic
    const { data, setData, post, processing, errors, reset } = useForm({
        name: '',
        email: '',
        password: '',
        password_confirmation: '',
    });

    // Handle form submission
    const submit = (e) => {
        e.preventDefault();

        post(route('register'), {
            // clear password fields after attempt for security
            onFinish: () => reset('password', 'password_confirmation'),
        });
    };

    return (
        <div className="min-h-screen flex items-center justify-center bg-base-200 px-4 py-12">
            <Head title="Register" />

            <div className="w-full max-w-md">
                <div className="text-center mb-8">
                    <h1 className="text-3xl font-bold">Create Account</h1>
                    <p className="text-sm">Join us to get started</p>
                </div>

                <div className="card shadow-lg">
                    <div className="card-body">
                        <form onSubmit={submit} className="space-y-5">
                            <div>
                                <InputLabel htmlFor="name" value="Full Name" />
                                <TextInput
                                    id="name"
                                    type="text"
                                    name="name"
                                    value={data.name}
                                    autoComplete="name"
                                    isFocused={true}
                                    onChange={(e) => setData('name', e.target.value)}
                                    placeholder="John Doe"
                                    required
                                />
                                <InputError message={errors.name} className="mt-1" />
                            </div>

                            <div>
                                <InputLabel htmlFor="email" value="Email Address" />
                                <TextInput
                                    id="email"
                                    type="email"
                                    name="email"
                                    value={data.email}
                                    autoComplete="email"
                                    onChange={(e) => setData('email', e.target.value)}
                                    placeholder="you@example.com"
                                    required
                                />
                                <InputError message={errors.email} className="mt-1" />
                            </div>

                            <div>
                                <InputLabel htmlFor="password" value="Password" />
                                <TextInput
                                    id="password"
                                    type="password"
                                    name="password"
                                    value={data.password}
                                    autoComplete="new-password"
                                    onChange={(e) => setData('password', e.target.value)}
                                    placeholder="••••••••"
                                    required
                                />
                                <InputError message={errors.password} className="mt-1" />
                            </div>

                            <div>
                                <InputLabel
                                    htmlFor="password_confirmation"
                                    value="Confirm Password"
                                />
                                <TextInput
                                    id="password_confirmation"
                                    type="password"
                                    name="password_confirmation"
                                    value={data.password_confirmation}
                                    autoComplete="new-password"
                                    onChange={(e) =>
                                        setData('password_confirmation', e.target.value)
                                    }
                                    placeholder="••••••••"
                                    required
                                />
                                <InputError
                                    message={errors.password_confirmation}
                                    className="mt-1"
                                />
                            </div>

                            <PrimaryButton
                                className="w-full"
                                disabled={processing}
                            >
                                {processing ? 'Creating account...' : 'Create Account'}
                            </PrimaryButton>
                        </form>

                        <div className="divider">OR</div>

                        <p className="text-center text-sm">
                            Already have an account?{' '}
                            <Link href={route('login')} className="underline">
                                Sign in
                            </Link>
                        </p>
                    </div>
                </div>

                <p className="mt-6 text-center text-xs">
                    By creating an account, you agree to our terms of service
                </p>
            </div>
        </div>
    );
}

// resources/js/Pages/Auth/Register.vue
<template>
  <Head title="Register" />
  <div class="login-bg">
    <div class="login-inspiration-container">
      <div class="login-inspiration-form">
        <div class="login-inspiration-header">
          <div class="login-inspiration-branding">
            <img :src="logoUrl" alt="sTracker Logo" class="login-inspiration-logo" />
            <div>
              <div class="login-inspiration-brand">sTracker</div>
              <p class="login-inspiration-brand-copy">Create your account and start tracking smarter.</p>
            </div>
          </div>
          <div class="login-inspiration-header-actions">
            <span class="login-inspiration-register">
              Already have an account?
              <Link :href="route('login')" class="login-inspiration-register-link">Sign in</Link>
            </span>
          </div>
        </div>

        <div class="login-inspiration-card">
          <div class="login-inspiration-card-header">
            <span class="login-inspiration-eyebrow">Get started</span>
            <div class="login-inspiration-title">Create your finance workspace</div>
            <p class="login-inspiration-description">
              Set up your account to manage transactions, monitor trends, and keep your financial overview organized.
            </p>
            <div class="login-inspiration-chip-row">
              <span class="login-inspiration-chip">Quick setup</span>
              <span class="login-inspiration-chip">Private account</span>
              <span class="login-inspiration-chip">Clear dashboard</span>
            </div>
          </div>

          <form @submit.prevent="submit" class="login-inspiration-form-fields">
            <div class="login-inspiration-inputs">
              <div>
                <InputLabel htmlFor="name" value="Full Name" class="login-label" />
                <TextInput
                  id="name"
                  type="text"
                  name="name"
                  v-model="form.name"
                  autocomplete="name"
                  :isFocused="true"
                  placeholder="John Doe"
                  class="login-input"
                  required
                />
                <InputError :message="form.errors.name" class="mt-1" />
              </div>

              <div>
                <InputLabel htmlFor="email" value="Email Address" class="login-label" />
                <TextInput
                  id="email"
                  type="email"
                  name="email"
                  v-model="form.email"
                  autocomplete="username"
                  placeholder="you@example.com"
                  class="login-input"
                  required
                />
                <InputError :message="form.errors.email" class="mt-1" />
              </div>

              <div>
                <InputLabel htmlFor="password" value="Password" class="login-label" />
                <TextInput
                  id="password"
                  type="password"
                  name="password"
                  v-model="form.password"
                  autocomplete="new-password"
                  placeholder="Create a strong password"
                  class="login-input"
                  required
                />
                <InputError :message="form.errors.password" class="mt-1" />
              </div>

              <div>
                <InputLabel htmlFor="password_confirmation" value="Confirm Password" class="login-label" />
                <TextInput
                  id="password_confirmation"
                  type="password"
                  name="password_confirmation"
                  v-model="form.password_confirmation"
                  autocomplete="new-password"
                  placeholder="Repeat your password"
                  class="login-input"
                  required
                />
                <InputError :message="form.errors.password_confirmation" class="mt-1" />
              </div>
            </div>

            <div class="login-inspiration-helper-box">
              <strong>Quick tip:</strong> Use an email you check often so you can recover your account easily and stay updated.
            </div>

            <div class="login-inspiration-actions">
              <PrimaryButton class="login-btn login-inspiration-btn" :disabled="form.processing">
                {{ form.processing ? 'Creating account...' : 'Create Account' }}
              </PrimaryButton>
            </div>
          </form>

          <div class="login-inspiration-support-row">
            <span class="login-inspiration-support-text">By creating an account, you can start organizing your finances right away.</span>
          </div>
        </div>

        <div class="login-inspiration-footer">© 2026 sTracker.</div>
      </div>

      <div class="login-inspiration-preview">
        <div class="login-inspiration-preview-glow login-inspiration-preview-glow-one"></div>
        <div class="login-inspiration-preview-glow login-inspiration-preview-glow-two"></div>
        <div class="login-inspiration-image-showcase">
          <div class="login-inspiration-dashboard-frame">
            <img
              :src="dashboardPreviewUrl"
              alt="sTracker dashboard preview"
              class="login-inspiration-preview-img"
            />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import dashboardPreviewUrl from '@/../../public/images/dashboard-preview.png';
import logoUrl from '@/../../public/images/stracker-logo.png';
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import TextInput from '@/Components/TextInput.vue';
import { Head, Link, useForm } from '@inertiajs/vue3';

const form = useForm({
  name: '',
  email: '',
  password: '',
  password_confirmation: ''
});

function submit() {
  form.post('/register', {
    onFinish: () => form.reset('password', 'password_confirmation'),
  });
}
</script>

<style scoped>
@import '../../../css/login.css';
</style>
